CREATE TABLE "GCG_4414_WIPFG_IMP"(
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "CHARGE_DATE" DATE,
 "CLOSE_FLAG" CHAR(1),
 "PART_DESC" CHAR(30),
 "QUANTITY" NUMERIC(12,4),
 "PROCESS_FLAG" CHAR(1) DEFAULT 'N' NOT NULL ,
 "ERROR_MSG" CHAR(50),
 "IDKEY" IDENTITY DEFAULT '0',
 UNIQUE ("IDKEY"));